length = int(input("집의 크기는 얼마로 할까요?"))

import turtle
t=turtle.Turtle()
t.shape("turtle")
t.forward(length)
t.left(120)
t.forward(length)
t.left(120)
t.forward(length)
t.left(30)
t.forward(length)
t.left(90)
t.forward(length)
t.left(90)
t.forward(length)
